In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
# getting data set
df = pd.read_csv("SPAM text message 20170820 - Data.csv")

In [3]:
df.shape

(5572, 2)

In [4]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
le = LabelEncoder()

In [6]:
df_encoded = df.apply(le.fit_transform,axis=0)

In [7]:
df_encoded.head()

Category  Message
0         0     1080
1         0     3126
2         1      999
3         0     4121
4         0     2781

In [8]:
df = df_encoded.values
df

array([[   0, 1080],
       [   0, 3126],
       [   1,  999],
       ...,
       [   0, 3313],
       [   0, 3932],
       [   0, 3437]])

In [9]:
X = df[:,1:]
# X = df[:,1]
type(df[:,1:])
X

array([[1080],
       [3126],
       [ 999],
       ...,
       [3313],
       [3932],
       [3437]])

In [10]:
type(df[:,1])

numpy.ndarray

In [11]:
y = df[:,0]
y

array([0, 0, 1, ..., 0, 0, 0])

In [12]:
X_train, y_train, X_test, y_test = train_test_split(
    X,y,test_size = 0.20, random_state = 42
)

# Posterior Probability
## Likely hood
## Prior Probab

In [13]:
def prior_probab(y_train,label):
    m = y_train.shape[0]
    s = np.sum(y_train == label)
    return m/s

In [14]:
def cond_probab(X_train,y_train,feature_col,feature_val,label):
    X_filtered = X_train[y_train == label]
    num = np.sum(X_filtered[:,feature_col] == feature_val)
    denom = X_filtered.shape[0]
    
    return float(num/denom)

In [15]:
def predict(X_train,y_train, X_test):
    classes = np.unique(y_train)
    n_features = X_train.shape[1]
    posterior_probab = []
    
    for label in classes:
        likelyhood = 1.0
        for fea in range(n_features):
            cond = cond_probab(X_train, y_train, fea, X_test[fea], label)
            likelyhood = likelyhood * cond
            
        prior = prior_probab(y_train, label)
        post = likelyhood * prior
        
        posterior_probab.append(post)
        
        pred = np.argmax(posterior_probab)
        
        return pred

In [16]:
def accuracy(X_train, y_train, X_test, y_test):
    pred = []
    
    for i in range(X_test.shape[0]):
        p = predict(X_train, y_train, X_test[i])
        pred.append(p)
        
    y_pred = np.array(pred)
    acc = np.sum(y_pred == y_test)/y_pred.shape[0]
    
    return acc

In [17]:
accuracy(X_train, y_train, X_test, y_test)

IndexError: invalid index to scalar variable.

In [ ]:
acc*100